POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "nami",
    "password": "90006080"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "vamsi",
    "password": "90006080"
}
###

GET http://localhost:3000/users
###

GET http://localhost:3000/diary-entries